name: Go

on:
  push:
    branches:
      - main
      - 'releases/**'
      - '!releases/**-alpha'
  pull_request:
    branches: [ main ]
  release:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...
